name: svg
description: generate svgs for markdown documentations
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  tikd:
     git: https://github.com/liyuqian/tikd
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
