name: roadart
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.6

dependencies:
  args: ^2.4.2
  crypto: ^3.0.6
  freezed_annotation: ^2.4.1
  glob: ^2.1.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  grpc: ^4.0.1
  http: ^1.2.2
  image: ^4.3.0
  json_annotation: ^4.8.1
  path: ^1.9.0
  process_run: ^1.2.2+1
  protobuf: ^3.1.0
  vector_math: ^2.1.4
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^5.1.1
  test: ^1.24.0
