name: roadart
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.6

dependencies:
  freezed_annotation: ^2.4.1
  glob: ^2.1.2
  grpc: ^3.2.4
  json_annotation: ^4.8.1
  path: ^1.9.0
  protobuf: ^3.1.0
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
