name: roadart
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.6

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
